version: "3"

services:
  influxdb:
    image: influxdb:2.0
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - 8086:8086
    restart: always

  collector:
    build:
      context: .
      dockerfile: ./collect/Dockerfile
    env_file: .env
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    restart: always

volumes:
  influxdb_data:
    driver: local
